# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: debug-statements

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Must be kept in sync with pyproject.toml
    rev: v0.5.5 # Check for the latest ruff version matching your pyproject.toml
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0 # Check for latest mypy version, align with pyproject.toml
    hooks:
    -   id: mypy
        # args: [--config-file=pyproject.toml] # mypy should pick up pyproject.toml by default
        additional_dependencies: [
            # Add any types packages your project uses that mypy needs for stubs
            # e.g., types-requests, types-beautifulsoup4 (if bs4 has stubs)
            # For now, assuming mypy.overrides in pyproject.toml handles missing imports for some libs
            "beautifulsoup4>=4.11.1", # So mypy can see bs4
            "html2text>=2020.1.16",
            # "weasyprint>=55.0", # Removed
            "fire>=0.4.0",
        ]
        # verbose: true # Optional: for more detailed mypy output
        # pass_filenames: false # If mypy should run on all files configured in pyproject.toml
                               # instead of just changed files. Usually True is fine.
